

target 'No More Paywall' do
    
pod 'Onboard'
pod 'KINWebBrowser'
pod 'VTAcknowledgementsViewController'
pod 'DZNEmptyDataSet'
pod 'SVProgressHUD'
end

target 'Incognito' do
pod 'CRToast'
end

post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
        if target.name.start_with? "Pods-Incognito"
            target.build_configurations.each do |config|
                config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'AF_APP_EXTENSIONS=1']
            end
        end
    end
end


